forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired
from wtforms import SearchField, SubmitField, RadioField, SelectField
from wtforms.validators import DataRequired


class SearchForm(FlaskForm):
    search = SearchField(label='Поиск', validators=[DataRequired()])
    search_type = RadioField(
        'Тип поиска', [DataRequired()],
        choices=[('string_search', 'точный поиск'),
                 ('ngram_search', 'неточный поиск')],
        default='ngram_search')
    submit = SubmitField(label='Найти')


class SearchFormProduct(SearchForm):
    maker = SelectField(
        'Тип поиска', [DataRequired()],
        choices=['ALL', 'PALBIT', 'YG-1', 'VERGNANO', 'VARGUS', 'SANHOG',
                 'OMAP', 'NANOLOY', 'LIKON', 'HORN', 'HELION',
                 'GABRIEL_MAUVAIS', 'FRESAL', 'DEREK', 'BRICE', 'Bribase',
                 'ASKUP', 'ILIX'],
        default='ALL')


class UploadForm(FlaskForm):
    file = FileField(validators=[FileRequired()])

src/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired
from wtforms import RadioField, SearchField, SelectField, SubmitField
from wtforms.validators import DataRequired


class SearchForm(FlaskForm):
    search = SearchField(label='Search', validators=[DataRequired()])
    search_type = RadioField(
        'Search type', [DataRequired()],
        choices=[('string_search', 'accurate search'),
                 ('ngram_search', 'elasticsearch')],
        default='ngram_search')
    submit = SubmitField(label='Search')


class SearchFormProduct(SearchForm):
    maker = SelectField(
        'Search type', [DataRequired()],
        choices=['ALL', 'PALBIT', 'YG-1', 'VERGNANO', 'VARGUS', 'SANHOG',
                 'OMAP', 'NANOLOY', 'LIKON', 'HORN', 'HELION',
                 'GABRIEL_MAUVAIS', 'FRESAL', 'DEREK', 'BRICE', 'Bribase',
                 'ASKUP', 'ILIX'],
        default='ALL')


class UploadForm(FlaskForm):
    file = FileField(validators=[FileRequired()])

app.py
from flask_bootstrap import Bootstrap4
from flask_migrate import Migrate

import flask_login
from flask import Flask

from auth.views import user_auth
from core.conf import FlaskConfig
from src.ctx_processor import year_processor
from src.database import db
from auth.users import load_user, handle_needs_login
from src.views import analog


def create_app():
    analog_app = Flask(__name__)
    analog_app.config.from_object(FlaskConfig)
    login_manager = flask_login.LoginManager()
    login_manager.init_app(analog_app)
    login_manager.user_loader(load_user)
    login_manager.unauthorized_handler(handle_needs_login)
    Bootstrap4(analog_app)
    db.init_app(analog_app)
    Migrate(analog_app, db)
    analog_app.context_processor(year_processor)
    analog_app.register_blueprint(analog, url_prefix='')
    analog_app.register_blueprint(user_auth, url_prefix='/auth')
    return analog_app


if __name__ == '__main__':
    create_app().run(host='0.0.0.0')

src/views.py
import aiofiles.os
from werkzeug.exceptions import NotFound, abort
from flask import (render_template, send_from_directory, Blueprint)
from flask_login import login_required
from core.conf import BASE_DIR
from src.forms import SearchForm, SearchFormProduct, UploadForm
from utils.async_funcs import fetch, fetch_file
from utils.choices import Response_type
from utils.data_models import HTTPResponse
from utils.form_utils import save_form_file


analog = Blueprint('analog', __name__,
                   template_folder=BASE_DIR / 'templates',
                   static_folder=BASE_DIR / 'static')


@analog.route('/', methods=['GET', 'POST'])
async def index():
    template_name = 'index.html'
    form = SearchForm()
    if form.validate_on_submit():
        url = f'http://analoghub.servebeer.com/api/v1/analog/search_analog'
        query = {'query': form.search.data,
                 'search_type': form.search_type.data}
        response: HTTPResponse = await fetch(url, query)
        if response.status == 404:
            return render_template(template_name, form=form, not_found=True)
        return render_template(template_name, form=form, result=response.body)
    return render_template(template_name, form=form)


@analog.route('/search_product', methods=['GET', 'POST'])
async def search_product():
    form = SearchFormProduct()
    if form.validate_on_submit():
        url = f'http://analoghub.servebeer.com/api/v1/analog/search_product'
        query = {'query': form.search.data,
                 'search_type': form.search_type.data,
                 'maker': form.maker.data}
        response: HTTPResponse = await fetch(url, query)
        if response.status == 404:
            return render_template('search_product.html', form=form,
                                   not_found=True)
        return render_template('search_product.html', form=form,
                               result=response.body)
    return render_template('search_product.html', form=form)


@analog.route('/upload_xlsx', methods=['GET', 'POST'])
@login_required
async def upload_xlsx():
    form = UploadForm()
    if form.validate_on_submit():
        file_path, file_name = save_form_file(form)
        url = f'http://analoghub.servebeer.com/api/v1/analog/upload_analogs'
        response = await fetch_file(url, file_path, file_name, 'xlsx_file')
        await aiofiles.os.remove(file_path)
        return {'response': response.status, 'detail': response.body}
    return render_template('upload_xlsx.html', form=form)


@analog.route('/upload_zip', methods=['GET', 'POST'])
@login_required
async def upload_zip():
    form = UploadForm()
    if form.validate_on_submit():
        file_path, file_name = save_form_file(form)
        url = f'http://analoghub.servebeer.com/api/v1/analog/upload_makers'
        response = await fetch_file(url, file_path, file_name, 'zip_file')
        await aiofiles.os.remove(file_path)
        return render_template(
            'upload_zip.html', form=form, result=response.body)
    return render_template('upload_zip.html', form=form)


@analog.route('/search_analogs_list', methods=['GET', 'POST'])
async def search_analogs_list():
    form = UploadForm()
    if form.validate_on_submit():
        file_path, file_name = save_form_file(form)
        url = f'http://analoghub.servebeer.com/api/v1/analog/search_list_analogs'
        response_file = await fetch_file(
            url, file_path, file_name, 'xlsx_file', Response_type.Xlsx)
        await aiofiles.os.remove(file_path)
        return render_template(
            'search_analog_list.html', form=form, resonse_file=response_file)
    return render_template('search_analog_list.html', form=form)


@analog.route('/get_file/<string:file_name>', methods=['GET'])
def get_file(file_name: str):
    try:
        return send_from_directory(
            BASE_DIR.joinpath('static'), file_name, as_attachment=True)
    except NotFound:
        abort(404)

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% block styles %}
            {{ bootstrap.load_css() }}
        {% endblock %}
        {% block title %}<title>Your page title</title>{% endblock %}
        {% endblock %}
    </head>
    <body class="d-flex flex-column min-vh-100">
        {% include 'includes/nav.html' %}
        <main>
            <div class="container">
            <h1>{% block header %}{% endblock %}</h1>
                <div class="card">
                    <div class="card-body">
                        {% block content %}{% endblock %}
                    </div>
                </div>
            </div>
        </main>
        <div class="wrapper flex-grow-1"></div>
        {% include 'includes/footer.html' %}
        {% block scripts %}
            {{ bootstrap.load_js() }}
        {% endblock %}
    </body>
</html>

templates/helpers.html
{% macro render_field(field,cls,errcls) %}

  {% if field.errors %}
  <div class="form-group">
    <label for="{{ field.id}}">{{ field.label.text }}</label>
    
    {{ field(class = cls + " " + errcls,**kwargs) | safe}}
    <div class="invalid-feedback">
      {% for error in field.errors %}
      <span> {{error}}</span>
      {% endfor %}
    </div>
  </div>

  {% else %}

  <div class="form-group">
    <label for="{{ field.id}}">{{ field.label.text }}</label>
    {{ field(class = cls,**kwargs) | safe}}
  </div>
  
  {% endif %}
{% endmacro %}

templates/includes/file_form.html
<form action="{{ url_action }}" method="post" enctype="multipart/form-data">
    {{ form.csrf_token }}
    <div class="input-group">
        <div class="custom-file">
            {{ form.file(class="custom-file-input") }}
            <label class="custom-file-label" for="{{ form.file.id }}">Choose File</label>
        </div>
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="submit" id="{{ form.file.id }}">Upload</button>
        </div>
    </div>
</form>
<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.js"></script>
<script src="{{ url_for('static', filename='/js/load_file_init.js') }}"></script>

templates/includes/footer.html
<footer class="pt-4 my-md-0 pt-md-3 border-top bg-dark">
{#        <p class="m-0 text-light text-center "><a href="#">Об авторе</a> - <a href="#">Технологии</a></p>#}
        <p class="m-1 text-light text-center">Project tool helper - <span style="color:yellow">Analog</span> Hub © {{ year }}, All rights reserved.</p>
</footer>

templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ url_for('analog.index') }}"><span style="color:yellow">Analog</span> Hub</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item {% if url_for(request.endpoint) == url_for('analog.index') %}active{% endif %}">
        <a class="nav-link" href="{{ url_for('analog.index') }}">Search Analogs</a>
      </li>
      <li class="nav-item {% if url_for(request.endpoint) == url_for('analog.search_product') %}active{% endif %}" >
        <a class="nav-link" href="{{ url_for('analog.search_product') }}">Search Products</a>
      </li>
      <li class="nav-item {% if url_for(request.endpoint) == url_for('analog.search_analogs_list') %}active{% endif %}">
        <a class="nav-link" href="{{ url_for('analog.search_analogs_list') }}">Search list analogs</a>
      </li>
        {% if current_user.is_authenticated and current_user.is_active %}
          <li class="nav-item {% if url_for(request.endpoint) == url_for('analog.upload_xlsx') %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('analog.upload_xlsx') }}">Load analogs</a>
          </li>
          <li class="nav-item {% if url_for(request.endpoint) == url_for('analog.upload_zip') %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('analog.upload_zip') }}">Load products</a>
          </li>
          <li class="nav-item {% if url_for(request.endpoint) == url_for('auth.logout') %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item {% if url_for(request.endpoint) == url_for('auth.login') %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
          </li>
        {% endif %}
    </ul>
  </div>
</nav>

templates/includes/result_file.html
{% if result %}
    <br>
    <div class="card">
        <div class="card-body">
            <p class="card-text"><a href="{{ url_for('get_file', file_name=result) }}">Download file</a></p>
        </div>
    </div>
{% endif %}

templates/includes/result_upload.html
{% if result %}
    <br>
    <div class="card">
        <div class="card-body">
            <p class="card-text">{{ result }}</p>
        </div>
    </div>
    <br>
{% endif %}

templates/index.html
{% extends "base.html" %}
{% block title %}<title>Поиск аналогов инструмента</title>{% endblock %}
{% block content %}
    <form method="POST" action="{{ url_for('analog.index') }}">
        {{ form.csrf_token }}
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                {{ form.submit(class="btn btn-outline-secondary") }}
            </div>
            {{ form.search(class="form-control", placeholder="") }}
        </div>
        <div class="btn-group btn-group-toggle" data-toggle="buttons">
            {% for subfield in form.search_type %}
                <label class="btn btn-outline-secondary btn-sm {% if subfield.label == 'ngram_search' %}active{% endif %}">
                    {{ subfield() }}
                    {{ subfield.label }}
                </label>
            {% endfor %}
        </div>
     </form>

    {% if not_found %}
        <div class="card mt-3">
            <div class="card-body">
                <p class="card-text">Не найдено</p>
            </div>
        </div>
    {% endif %}
    {% if result %}
        {% for item in result %}
            <div class="card mt-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm">
                            <p class="card-text">Исходный инструмент: {{ item.base_name }} {{ item.base_maker }} <br> Аналог: {{ item.analog_name }} {{ item.analog_maker }}</p>
                        </div>
                        <div class="col-sm">
                            <button class="btn btn-secondary" data-clipboard-text="{{ item.analog_name }}">
                                Copy analog description
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    <script src="{{ url_for('static', filename='/js/dist/clipboard.min.js') }}"></script>
    <script src="{{ url_for('static', filename='/js/copy_init.js') }}"></script>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}<title>Поиск аналогов инструмента</title>{% endblock %}
{% block content %}
    {% if message %}
        <div class="card mb-3">
            <div class="card-body">
                <p class="card-text">{{ message }}</p>
            </div>
        </div>
    {% endif %}
    <form method="POST" action="{{ url_for('auth.login', next=request.args.get('next')) }}">
        {{ form.csrf_token }}
        <div class="form-group row">
            {{ form.username.label(class="col-sm-2 col-form-label") }}
            <div class="col-sm-10">
                {{ form.username(class="form-control") }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.password.label(class="col-sm-2 col-form-label") }}
            <div class="col-sm-10">
                {{ form.password(class="form-control") }}
            </div>
        </div>
        <div class="form-group row mb-0">
            <div class="col-sm-10">
                {{ form.submit(class="btn btn-secondary") }}
            </div>
        </div>
    </form>
{% endblock %}

templates/search_analog_list.html
{% extends "base.html" %}
{% block title %}<title>Поиск аналогов инструмента</title>{% endblock %}
{% block content %}
{% with url_action=url_for('analog.search_analogs_list'), form=form %}
    {% include "includes/file_form.html" %}
{% endwith %}
{% with result=resonse_file %}
    {% include "includes/result_file.html" %}
{% endwith %}
{% endblock %}

templates/search_product.html
{% extends "base.html" %}
{% block title %}<title>Поиск аналогов инструмента</title>{% endblock %}
{% block content %}
    <form method="POST" action="{{ url_for('analog.search_product') }}">
        {{ form.csrf_token }}
        <div class="input-group">
            <div class="input-group-prepend">
                {{ form.submit(class="btn btn-outline-secondary") }}
            </div>
            {{ form.search(class="form-control", placeholder="") }}
        </div>
        <div class="btn-group btn-group-toggle mt-3" data-toggle="buttons">
            {% for subfield in form.search_type %}
                <label class="btn btn-outline-secondary btn-sm {% if subfield.label == 'ngram_search' %}active{% endif %}">
                    {{ subfield() }}
                    {{ subfield.label }}
                </label>
            {% endfor %}
        </div>
        <div class="row mt-3 mb-0">
            <div class="col-3 mb-0">
                <div class="form-group mb-0">
                    {{ form.maker(class="form-control") }}
                </div>
            </div>
        </div>
    </form>

    {% if not_found %}
        <div class="card mt-3">
          <div class="card-body">
            <p class="card-text">Не найдено</p>
          </div>
        </div>
    {% endif %}
    {% if result %}
        {% for item in result %}
            <div class="card mt-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm">
                            <p class="card-text">{{ item.name }} {{ item.maker }}</p>
                        </div>
                        <div class="col-sm">
                            <button class="btn btn-secondary" data-clipboard-text="{{ item.name }}">
                                Copy description
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    <script src="{{ url_for('static', filename='/js/dist/clipboard.min.js') }}"></script>
    <script src="{{ url_for('static', filename='/js/copy_init.js') }}"></script>
{% endblock %}

templates/upload_xlsx.html
{% extends "base.html" %}
{% block title %}<title>Поиск аналогов инструмента</title>{% endblock %}
{% block content %}
{% with url_action=url_for('analog.upload_xlsx'), form=form %}
    {% include "includes/file_form.html" %}
{% endwith %}
{% with result=result %}
    {% include "includes/result_upload.html" %}
{% endwith %}
{% endblock %}

templates/upload_zip.html
{% extends "base.html" %}
{% block title %}<title>Поиск аналогов инструмента</title>{% endblock %}
{% block content %}
{% with url_action=url_for('analog.upload_zip'), form=form %}
    {% include "includes/file_form.html" %}
{% endwith %}
{% with result=result %}
    {% include "includes/result_upload.html" %}
{% endwith %}
{% endblock %}